# The system's topology, as compact JSON in one SSM parameter. The M5 agent
# reads it with get_topology to learn what exists and what depends on what,
# before it starts looking at metrics and logs.
#
# Structure, not state. It says which services exist, what each one calls,
# and which queues, tables and flags they use. It deliberately leaves out
# anything that changes with a deploy, such as the published version, timeout
# or memory size: those are exactly what some scenarios change, and the agent
# must read their live values (get_function_config, list_recent_deployments)
# rather than trust a snapshot. It also means this parameter only changes when
# the architecture does.
#
# Built from resource attributes, so a renamed queue or table updates the
# topology in the same apply. The `calls` lists are written by hand and must
# match the services' IAM policies in services.tf.
#
# Unlike the flags, Terraform owns this value outright: it is generated, and
# nobody edits it during an incident.

locals {
  topology = {
    v      = 1
    region = local.region
    services = {
      cart = {
        function  = module.cart.function_name
        alias     = "live"
        log_group = module.cart.log_group_name
        entry     = ["function_url", "invoke"]
        calls     = []
        stores    = ["dynamodb:${aws_dynamodb_table.cart.name}"]
        flags     = []
      }
      orders = {
        function  = module.orders.function_name
        alias     = "live"
        log_group = module.orders.log_group_name
        entry     = ["function_url"]
        calls     = ["cart"]
        stores    = ["dsql"]
        publishes = [aws_sqs_queue.placed_orders.name]
        flags     = [aws_ssm_parameter.checkout_rate_limit.name]
      }
      fulfillment = {
        function  = module.fulfillment.function_name
        alias     = "live"
        log_group = module.fulfillment.log_group_name
        entry     = ["sqs:${aws_sqs_queue.placed_orders.name}"]
        calls     = ["payments"]
        stores    = ["dsql"]
        flags     = [aws_ssm_parameter.payments_degraded_mode.name]
      }
      payments = {
        function  = module.payments.function_name
        alias     = "live"
        log_group = module.payments.log_group_name
        entry     = ["invoke"]
        calls     = []
        stores    = []
        flags     = []
        # A mock of a third-party API. In a real system this would be outside
        # our control, so fixing it is never an available action.
        external = true
      }
    }
    queues = {
      (aws_sqs_queue.placed_orders.name) = {
        consumer          = "fulfillment"
        dlq               = aws_sqs_queue.placed_orders_dlq.name
        max_receive_count = jsondecode(aws_sqs_queue.placed_orders.redrive_policy).maxReceiveCount
      }
    }
    tables = {
      # Billing mode only. Capacity is state: it can be changed outside
      # Terraform, and a snapshot here would quietly mislead the agent.
      (aws_dynamodb_table.cart.name) = {
        billing = aws_dynamodb_table.cart.billing_mode
      }
    }
    dsql = {
      cluster_id = aws_dsql_cluster.main.identifier
    }
    metrics_namespace = "NightShift"
  }

  topology_json = jsonencode(local.topology)
}

resource "aws_ssm_parameter" "topology" {
  name        = "/${var.project}/topology"
  description = "Service topology for the on-call agent. Generated by Terraform from terraform/topology.tf; do not edit by hand."
  type        = "String"
  tier        = "Standard"
  value       = local.topology_json

  lifecycle {
    # The Standard tier holds at most 4 KB. Over that, SSM would require the
    # Advanced tier, which is billed per parameter per month and can never be
    # downgraded. Fail the plan instead of drifting into it.
    #
    # length() counts characters, not bytes, so the second condition makes
    # sure every character is one byte (ASCII) and the count is honest.
    precondition {
      condition     = length(local.topology_json) <= 4096 && can(regex("^[[:ascii:]]*$", local.topology_json))
      error_message = "Topology JSON is ${length(local.topology_json)} characters; the Standard tier limit is 4096 bytes of ASCII. Trim it rather than moving to the Advanced tier."
    }
  }
}

output "topology_bytes" {
  description = "Size of the topology parameter. The Standard tier limit is 4096."
  value       = length(local.topology_json)
}
