-- The catalogue. Products are read constantly and written almost never.
--
-- UUID primary keys, generated by the application rather than by a sequence.
-- DSQL distributes data by primary key, so sequential keys concentrate writes
-- on one range and random ones spread them out. That matters here: scenario 7
-- deliberately creates hot-row contention, and it is only a useful test if
-- the default is not already contended.
CREATE TABLE IF NOT EXISTS products (
    product_id  UUID PRIMARY KEY,
    sku         TEXT NOT NULL,
    name        TEXT NOT NULL,
    price_cents INTEGER NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
